[pytest]
testpaths = tests
python_files = test_*.py
addopts = -q --tb=short --ignore=tests/test_apis.py --ignore=tests/test_both_users.py --ignore=tests/test_cabys_api.py --ignore=tests/test_dashboard.py --ignore=tests/test_emission.py --ignore=tests/test_supabase_connection.py
filterwarnings =
    ignore::DeprecationWarning

